# Generated by Django 4.1 on 2022-09-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="category",
        ),
    ]
